services:
   
    db:
        image: postgres:16.3
        container_name: car_finder_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: car_finder_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - database:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        expose:
            - 5433
        networks:
            - car_finder

networks:
    car_finder:
        driver: bridge

volumes:
    database:
